[program:tailscale-login]
command=/opt/supervisor-scripts/tailscale-login.sh
autostart=true
autorestart=false

stdout_logfile=/var/log/tailscale-login.log
stderr_logfile=/var/log/tailscale-login.err.log