[program:tailscale]
command=/usr/sbin/tailscaled --tun=userspace-networking
autostart=true
autorestart=true
startretries=10

stdout_logfile=/var/log/tailscaled.log
stderr_logfile=/var/log/tailscaled.err.log

# keep it running in foreground
stopsignal=TERM
killasgroup=true
stopasgroup=true